#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : picocom
Version  : 3.1
Release  : 3
URL      : https://github.com/npat-efault/picocom/archive/3.1.tar.gz
Source0  : https://github.com/npat-efault/picocom/archive/3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: picocom-bin = %{version}-%{release}
Requires: picocom-license = %{version}-%{release}
Requires: picocom-man = %{version}-%{release}
Patch1: 0001-Fix-make-install.patch

%description
# picocom
Minimal dumb-terminal emulator
by Nick Patavalis (npat@efault.net)
The latest release can be downloaded from:

%package bin
Summary: bin components for the picocom package.
Group: Binaries
Requires: picocom-license = %{version}-%{release}

%description bin
bin components for the picocom package.


%package doc
Summary: doc components for the picocom package.
Group: Documentation
Requires: picocom-man = %{version}-%{release}

%description doc
doc components for the picocom package.


%package license
Summary: license components for the picocom package.
Group: Default

%description license
license components for the picocom package.


%package man
Summary: man components for the picocom package.
Group: Default

%description man
man components for the picocom package.


%prep
%setup -q -n picocom-3.1
cd %{_builddir}/picocom-3.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604605328
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604605328
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/picocom
cp %{_builddir}/picocom-3.1/LICENSE.txt %{buildroot}/usr/share/package-licenses/picocom/c3a0baba9a8daedb6294447a21993439d076dd9e
cp %{_builddir}/picocom-3.1/linenoise-1.0/LICENSE %{buildroot}/usr/share/package-licenses/picocom/3bd655bcdbe6f4f14e9da385f1953c50dd89ea8e
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pcasc
/usr/bin/pcxm
/usr/bin/pcym
/usr/bin/pczm
/usr/bin/picocom

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/picocom/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/picocom/3bd655bcdbe6f4f14e9da385f1953c50dd89ea8e
/usr/share/package-licenses/picocom/c3a0baba9a8daedb6294447a21993439d076dd9e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/picocom.1
